## Exercise on Functions


### Task 1: Create a Python program that converts between different units of measurement.

In [101]:
def convert_length(value, unit):
    """
    Convert length between meters and feet.
    :param value: The numerical value to convert.
    :param unit: The unit to convert from ('m' for meters, 'ft' for feet).
    :return: Converted value.
    """
    if unit == 'm':
        return value * 3.28084  # Meters to feet
    elif unit == 'ft':
        return value / 3.28084  # Feet to meters
    else:
        raise ValueError("Unsupported length unit.")

def convert_weight(value, unit):
    """
    Convert weight between kilograms and pounds.
    :param value: The numerical value to convert.
    :param unit: The unit to convert from ('kg' for kilograms, 'lbs' for pounds).
    :return: Converted value.
    """
    if unit == 'kg':
        return value * 2.20462  # Kilograms to pounds
    elif unit == 'lbs':
        return value / 2.20462  # Pounds to kilograms
    else:
        raise ValueError("Unsupported weight unit.")

def convert_volume(value, unit):
    """
    Convert volume between liters and gallons.
    :param value: The numerical value to convert.
    :param unit: The unit to convert from ('L' for liters, 'gal' for gallons).
    :return: Converted value.
    """
    if unit == 'L':
        return value * 0.264172  # Liters to gallons
    elif unit == 'gal':
        return value / 0.264172  # Gallons to liters
    else:
        raise ValueError("Unsupported volume unit.")

def main():
    """Main function to handle user input and conversion selection."""
    print("Unit Converter: Length, Weight, Volume")
    print("1. Length (meters to feet, feet to meters)")
    print("2. Weight (kilograms to pounds, pounds to kilograms)")
    print("3. Volume (liters to gallons, gallons to liters)")
    
    try:
        choice = int(input("Select conversion type (1-3): "))
        value = float(input("Enter value to convert: "))
        
        if choice == 1:
            unit = input("Enter unit ('m' for meters, 'ft' for feet): ").strip().lower()
            result = convert_length(value, unit)
            new_unit = 'ft' if unit == 'm' else 'm'
        elif choice == 2:
            unit = input("Enter unit ('kg' for kilograms, 'lbs' for pounds): ").strip().lower()
            result = convert_weight(value, unit)
            new_unit = 'lbs' if unit == 'kg' else 'kg'
        elif choice == 3:
            unit = input("Enter unit ('L' for liters, 'gal' for gallons): ").strip().lower()
            result = convert_volume(value, unit)
            new_unit = 'gal' if unit == 'L' else 'L'
        else:
            print("Invalid choice. Please select a valid option.")
            return
        
        print(f"Converted value: {result:.2f} {new_unit}")
    
    except ValueError as e:
        print(f"Error: {e}. Please enter valid input.")

if __name__ == "__main__":
    main()


Unit Converter: Length, Weight, Volume
1. Length (meters to feet, feet to meters)
2. Weight (kilograms to pounds, pounds to kilograms)
3. Volume (liters to gallons, gallons to liters)


Select conversion type (1-3):  1
Enter value to convert:  1
Enter unit ('m' for meters, 'ft' for feet):  ft


Converted value: 0.30 m


### Task 2: Create a Python program that performs various mathematical operations on a list of numbers.

In [102]:
def calculate_sum(numbers):
    """
    The sum of a list of numbers is calculated.
    :param numbers: List of numerical values.
    :return: Sum of the numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    The average of a list of numbers is calculated.
    :param numbers: List of numerical values.
    :return: Average of the numbers.
    """
    return sum(numbers) / len(numbers) if numbers else 0  # Division by zero is avoided

def find_maximum(numbers):
    """
    The maximum value in a list of numbers is found.
    :param numbers: List of numerical values.
    :return: Maximum number.
    """
    return max(numbers)

def find_minimum(numbers):
    """
    The minimum value in a list of numbers is found.
    :param numbers: List of numerical values.
    :return: Minimum number.
    """
    return min(numbers)

def main():
    """Main function to handle user input and perform the selected operation."""
    print("Mathematical Operations on a List of Numbers")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")
    
    try:
        choice = int(input("Select an operation (1-4): "))
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))
        
        if not numbers:
            raise ValueError("List is empty. At least one number must be entered.")
        
        if choice == 1:
            result = calculate_sum(numbers)
            operation = "Sum"
        elif choice == 2:
            result = calculate_average(numbers)
            operation = "Average"
        elif choice == 3:
            result = find_maximum(numbers)
            operation = "Maximum"
        elif choice == 4:
            result = find_minimum(numbers)
            operation = "Minimum"
        else:
            print("An invalid choice was made. A valid option must be selected.")
            return

        print(f"{operation}: {result:.2f}")

    except ValueError as e:
        print(f"Error: {e}. Valid numerical input must be entered.")

if __name__ == "__main__":
    main()


Mathematical Operations on a List of Numbers
1. Sum
2. Average
3. Maximum
4. Minimum


Select an operation (1-4):  1
Enter numbers separated by spaces:  1 119


Sum: 120.00


## Exercise on List Manipulation

### Task 1: Write a Python function that extracts every other element from a list, starting from the first element.

In [103]:
def extract_every_other(lst):
    """
    Extract every other element from the list, starting from the first element.
    :param lst: List of elements.
    :return: A new list containing every other element.
    """
    return lst[::2]  # Using slicing to get every other element

# Example usage
input_list = [1, 2, 3, 4, 5, 6]
output_list = extract_every_other(input_list)
print("Output:", output_list)  # Output: [1, 3, 5]


Output: [1, 3, 5]


### Task 2: Write a Python function that returns a sublist from a given list, starting from a specified index and
###         ending at another specified index.

In [104]:
def get_sublist(lst, start, end):
    """
    Return a sublist from the given list, starting from the specified index and ending at another specified index (inclusive).
    :param lst: List of elements.
    :param start: Starting index.
    :param end: Ending index.
    :return: Sublist from start to end (inclusive).
    """
    return lst[start:end+1]  # Slicing to include the end index

# Example usage
input_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4
output_sublist = get_sublist(input_list, start_index, end_index)
print("Output:", output_sublist)  # Output: [3, 4, 5]


Output: [3, 4, 5]


### Task 3: Write a Python function that reverses a list using slicing.

In [105]:
def reverse_list(lst):
    """
    Reverse the given list using slicing.
    :param lst: List of elements.
    :return: Reversed list.
    """
    return lst[::-1]  # Slicing to reverse the list

# Example usage
input_list = [1, 2, 3, 4, 5]
output_list = reverse_list(input_list)
print("Output:", output_list)  # Output: [5, 4, 3, 2, 1]


Output: [5, 4, 3, 2, 1]


### Task 4: Write a Python function that removes the first and last elements of a list and returns the resulting
### sublist.

In [106]:
def remove_first_last(lst):
    """
    Remove the first and last elements from the list and return the resulting sublist.
    :param lst: List of elements.
    :return: Sublist without the first and last elements.
    """
    return lst[1:-1]  # Slicing to remove the first and last elements

# Example usage
input_list = [1, 2, 3, 4, 5]
output_list = remove_first_last(input_list)
print("Output:", output_list)  # Output: [2, 3, 4]


Output: [2, 3, 4]


### Task 5: Write a Python function that extracts the first n elements from a list.

In [107]:
def get_first_n(lst, n):
    """
    Extract the first n elements from the list using slicing.
    :param lst: List of elements.
    :param n: Number of elements to extract.
    :return: A list of the first n elements.
    """
    return lst[:n]  # Slicing to get the first n elements

# Example usage
input_list = [1, 2, 3, 4, 5]
n = 3
output_list = get_first_n(input_list, n)
print("Output:", output_list)  # Output: [1, 2, 3]


Output: [1, 2, 3]


### Task 6: Write a Python function that extracts the first n elements from a list.

In [108]:
def get_last_n(lst, n):
    """
    Extract the last n elements from the list using slicing.
    :param lst: List of elements.
    :param n: Number of elements to extract from the end.
    :return: A list of the last n elements.
    """
    return lst[-n:]  # Slicing to get the last n elements

input_list = [1, 2, 3, 4, 5]
n = 2
output_list = get_last_n(input_list, n)
print("Output:", output_list)  # Output: [4, 5]


Output: [4, 5]


### Task 7: Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between. 

In [109]:
def reverse_skip(lst):
    """
    Extract every second element starting from the second-to-last element and moving backward.
    :param lst: List of elements.
    :return: A list of every second element in reverse order starting from the second-to-last.
    """
    return lst[-2::-2]  # Slicing to get every second element starting from the second-to-last, moving backward

# Example usage
input_list = [1, 2, 3, 4, 5, 6]
output_list = reverse_skip(input_list)
print("Output:", output_list)  # Output: [5, 3, 1]


Output: [5, 3, 1]


## Exercise on Nested Loops

### Task 1: Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension. 


In [110]:
def flatten(lst):
    """
    Flatten a nested list into a single list.
    :param lst: Nested list to be flattened.
    :return: A flattened list.
    """
    flattened = []
    for item in lst:
        if isinstance(item, list):
            flattened.extend(flatten(item))  # Recursively flatten the nested list
        else:
            flattened.append(item)
    return flattened

# Example usage
nested_list = [[1, 2], [3, 4], [5]]
output = flatten(nested_list)
print("Output:", output)  # Output: [1, 2, 3, 4, 5]


Output: [1, 2, 3, 4, 5]


### Task 2: Write a Python function that extracts a specific element from a nested list given its indices.

In [ ]:
def access_nested_element(lst, indices):
    """
    Access an element from a nested list using a list of indices.
    :param lst: Nested list.
    :param indices: List of indices to access the element.
    :return: The element at the specified indices.
    """  
    for index in indices:
        lst = lst[index]  # Access the element at the current index
    return lst

# Example usage
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
output = access_nested_element(nested_list, indices)
print("Output:", output)  # Output: 6


Output: 6


### Task 3: Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

In [112]:
def sum_nested(lst):
    """
    Calculate the sum of all elements in a nested list (regardless of depth).
    :param lst: Nested list of numbers.
    :return: Sum of all elements.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # Recursively sum the nested lists
        else:
            total += item
    return total

# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
output = sum_nested(nested_list)
print("Output:", output)  # Output: 21

Output: 21


### Task 4: Write a Python function that removes all occurrences of a specific element from a nested list.

In [113]:
def remove_element(lst, elem):
    """
    Remove all occurrences of a specific element from a nested list.
    :param lst: Nested list.
    :param elem: Element to be removed.
    :return: Modified nested list with the element removed.
    """
    if isinstance(lst, list):
        return [remove_element(item, elem) for item in lst if item != elem]  # Recursively remove element
    return lst

# Example usage
nested_list = [[1, 2], [3, 2], [4, 5]]
elem = 2
output = remove_element(nested_list, elem)
print("Output:", output)  # Output: [[1], [3], [4, 5]]

Output: [[1], [3], [4, 5]]


### Task 5: Write a Python function that finds the maximum element in a nested list (regardless of depth).

In [114]:
def find_max(lst):
    """
    Find the maximum element in a nested list (regardless of depth).
    :param lst: Nested list of numbers.
    :return: The maximum element in the list.
    """
    max_element = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_element = max(max_element, find_max(item))  # Recursively find max in nested lists
        else:
            max_element = max(max_element, item)
    return max_element

# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
output = find_max(nested_list)
print("Output:", output)  # Output: 6


Output: 6


### Task 6: Write a Python function that counts how many times a specific element appears in a nested list.

In [115]:
def count_occurrences(lst, elem):
    """
    Count how many times a specific element appears in a nested list.
    :param lst: Nested list.
    :param elem: Element to count.
    :return: The number of occurrences of the element.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # Recursively count in nested lists
        elif item == elem:
            count += 1
    return count

# Example usage
nested_list = [[1, 2], [2, 3], [2, 4]]
elem = 2
output = count_occurrences(nested_list, elem)
print("Output:", output)  # Output: 3


Output: 3


### Task 7: Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

In [116]:
def deep_flatten(lst):
    """
    Flatten a deeply nested list of lists of lists into a single list.
    :param lst: Deeply nested list.
    :return: A flattened list.
    """
    flattened = []
    for item in lst:
        if isinstance(item, list):
            flattened.extend(deep_flatten(item))  # Recursively flatten deeply nested lists
        else:
            flattened.append(item)
    return flattened

# Example usage
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
output = deep_flatten(nested_list)
print("Output:", output)  # Output: [1, 2, 3, 4, 5, 6, 7, 8]


Output: [1, 2, 3, 4, 5, 6, 7, 8]


### Task 8: Write a Python function that calculates the average of all elements in a nested list

In [117]:
def average_nested(lst):
    """
    Calculate the average of all elements in a nested list.
    :param lst: Nested list of numbers.
    :return: The average of all elements.
    """
    total, count = 0, 0
    for item in lst:
        if isinstance(item, list):
            sub_total, sub_count = average_nested(item)  # Recursively get sum and count
            total += sub_total
            count += sub_count
        else:
            total += item
            count += 1
    return total, count  # Return both total and count

# Example usage
nested_list = [[1, 2], [3, 4], [5, 6]]
total, count = average_nested(nested_list)
average = total / count if count else 0  # Avoid division by zero
print("Average:", average)  # Output: 3.5


Average: 3.5


## To-do Numpy

## Problem 1: Array Creation

### Task 1: Initialize an empty array with size 2x2:

In [118]:
import numpy as np
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)


Empty Array:
 [[1.14e-322 2.52e-322]
 [6.42e-323 1.43e-322]]


### Task 2: Initialize an empty array with size 4x2:

In [119]:
ones_array = np.ones((4, 2))
print("All Ones Array:\n", ones_array)

All Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


### Task 3: Return a new array of a given shape and type, filled with a fill value:

In [120]:
filled_array = np.full((3, 3), 7)
print("Filled Array:\n", filled_array)


Filled Array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


### Task 4: Return a new array of zeros with the same shape and type as a given array:

In [121]:
template_array = np.array([[1, 2], [3, 4]])
zeros_array = np.zeros_like(template_array)
print("Zeros Array with Same Shape and Type:\n", zeros_array)


Zeros Array with Same Shape and Type:
 [[0 0]
 [0 0]]


### Task 5: Return a new array of ones with the same shape and type as a given array:

In [122]:
ones_like_array = np.ones_like(template_array)
print("Ones Array with Same Shape and Type:\n", ones_like_array)


Ones Array with Same Shape and Type:
 [[1 1]
 [1 1]]


### Task 6: Convert an existing list new_list = [1, 2, 3, 4] to a numpy array:

In [123]:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Numpy Array:\n", numpy_array)


Numpy Array:
 [1 2 3 4]


## Problem 2: Array Manipulation

### Task 1: Create an array with values ranging from 10 to 49.

In [124]:
array_range = np.arange(10, 50)
print("Array with values from 10 to 49:\n", array_range)

Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Task 2: Create a 3x3 matrix with values ranging from 0 to 8.

In [125]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print("3x3 Matrix with values from 0 to 8:\n", matrix_3x3)

3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


### Task 3: Create a 3x3 identity matrix.

In [126]:
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)


3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Task 4: Create a random array of size 30 and find the mean of the array.

In [127]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Mean of Random Array:", mean_value)


Mean of Random Array: 0.43035056010593326


### Task 5: Create a 10x10 array with random values and find the minimum and maximum values.

In [128]:
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


Minimum Value: 0.002191417326719791
Maximum Value: 0.9988178476242789


### Task 6: Create a zero array of size 10 and replace the 5th element with 1.

In [129]:
zero_array = np.zeros(10)
zero_array[4] = 1  # Index 4 corresponds to the 5th element
print("Zero Array with 5th Element as 1:\n", zero_array)


Zero Array with 5th Element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### Task 7: Reverse an array

In [130]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Reversed Array:\n", reversed_arr)

Reversed Array:
 [0 4 0 0 2 1]


### Task 8: Create a 2D array with 1 on the border and 0 inside:

In [131]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D Array with 1 on Border and 0 Inside:\n", border_array)

2D Array with 1 on Border and 0 Inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Task 9: Create an 8x8 matrix and fill it with a checkerboard pattern:

In [132]:
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard Pattern:\n", checkerboard)

8x8 Checkerboard Pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Problem 3: Array Operations

### For the following arrays:

In [133]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

### Task 1: Add the two arrays x and y.

In [134]:
sum_array = x + y
print("Sum of Arrays x and y:\n", sum_array)

Sum of Arrays x and y:
 [[ 6  8]
 [10 13]]


### Task 2: Subtract the two arrays x and y.

In [135]:
diff_array = x - y
print("Difference of Arrays x and y:\n", diff_array)

Difference of Arrays x and y:
 [[-4 -4]
 [-4 -3]]


### Task 3: Multiply the array x with an integer of your choice.

In [136]:
multiplied_array = x * 3  # Example with 3
print("Array x Multiplied by 3:\n", multiplied_array)

Array x Multiplied by 3:
 [[ 3  6]
 [ 9 15]]


### Task 4: Find the square of each element of the array x.

In [137]:
squared_array = np.square(x)
print("Square of Each Element in Array x:\n", squared_array)

Square of Each Element in Array x:
 [[ 1  4]
 [ 9 25]]


### Task 5: Find the dot product.

In [138]:
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("Dot product of v and w:", dot_vw)
print("Dot product of x and v:\n", dot_xv)
print("Dot product of x and y:\n", dot_xy)

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


### Task 6 : Concatenate x and y along rows and concatenate v and w along columns:

In [139]:
concatenated_xy_row = np.concatenate((x, y), axis=0)
concatenated_vw_col = np.concatenate((v[:, None], w[:, None]), axis=1)
print("Concatenated x and y along rows:\n", concatenated_xy_row)
print("Concatenated v and w along columns:\n", concatenated_vw_col)


Concatenated x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w along columns:
 [[ 9 11]
 [10 12]]


### Task 7: Concatenate x and v:

In [140]:
 ## np.concatenate((x, v)) 
# This raises a value error because the dimensions does not match for conatenation

## Problem 4: Matrix Operations

### For the following matrices:

In [141]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

### Task 1: Prove that A * A^(-1) = I.

In [142]:
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^(-1) = I:\n", identity_matrix)

A * A^(-1) = I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


### Task 2: Prove that AB ≠ BA.

In [143]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


### Task 3: Prove that (AB)^T = B^T * A^T.

In [144]:
transpose_AB = np.transpose(np.dot(A, B))
transpose_BA = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T:\n", transpose_AB)
print("B^T * A^T:\n", transpose_BA)

(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]


### Task 4: Solve the system of linear equations using inverse methods

In [145]:
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

X = np.linalg.inv(A_eq).dot(B_eq)
print("Solution using Inverse Method:", X)

Solution using Inverse Method: [ 2.  1. -2.]


## Problem 5: How Fast is Numpy?

### Task 1: Element-wise Addition:

In [146]:
import time

# Using Python Lists
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]
start_time = time.time()
list_addition = [list1[i] + list2[i] for i in range(1000000)]
print("Python List Addition Time:", time.time() - start_time)

# Using NumPy Arrays
array1 = np.array(list1)
array2 = np.array(list2)
start_time = time.time()
numpy_addition = array1 + array2
print("NumPy Array Addition Time:", time.time() - start_time)


Python List Addition Time: 0.04641580581665039
NumPy Array Addition Time: 0.0014531612396240234


### Task 2: Element-wise Multiplication:

In [147]:
# Using Python Lists
start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(1000000)]
print("Python List Multiplication Time:", time.time() - start_time)

# Using NumPy Arrays
start_time = time.time()
numpy_multiplication = array1 * array2
print("NumPy Array Multiplication Time:", time.time() - start_time)


Python List Multiplication Time: 0.050498247146606445
NumPy Array Multiplication Time: 0.0028989315032958984


### Task 3: Dot Product:

In [148]:
# Using Python Lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(1000000))
print("Python List Dot Product Time:", time.time() - start_time)

# Using NumPy Arrays
start_time = time.time()
dot_product_numpy = np.dot(array1, array2)
print("NumPy Array Dot Product Time:", time.time() - start_time)


Python List Dot Product Time: 0.047338008880615234
NumPy Array Dot Product Time: 0.0004940032958984375


### Task 4: Matrix Multiplication

In [149]:
import time
import numpy as np

# Using Python Lists
matrix1 = [[i for i in range(1000)] for j in range(1000)]
matrix2 = [[i for i in range(1000)] for j in range(1000)]
start_time = time.time()
matrix_multiplication_list = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]
print("Python List Matrix Multiplication Time:", time.time() - start_time)

# Using NumPy Arrays
matrix1_numpy = np.random.random((1000, 1000))
matrix2_numpy = np.random.random((1000, 1000))
start_time = time.time()
matrix_multiplication_numpy = np.dot(matrix1_numpy, matrix2_numpy)
print("NumPy Array Matrix Multiplication Time:", time.time() - start_time)

Python List Matrix Multiplication Time: 60.307302951812744
NumPy Array Matrix Multiplication Time: 0.02683424949645996
